### ISSUE TITLE
The Second query show invalid data

### ISSUE THREAD

**Issue by elkadeem** [3bkareno/Task_1#3]
The count of employees in each department contains employees who leaved the department (EndDate in the past)

- [x] Read the task
- [x] Write SQL Query that can help you to understand the data and to be used in the validation
- [x] Fix the issue in the query
- [x] Validate the result

**Comment by 3bkareno** [comment]
x.EmployeeDepartmentHistories.Where(x => x.EndDate == null).Select(x => x.BusinessEntityId).Count()

Added To the select statement
